### ISSUE TITLE
Missing materials.

### ISSUE THREAD

**Issue by Steedalion** [rparak/Unity3D_Robotics_UR#2]
Floor and roof materials are missing.

**Comment by Steedalion** [comment]
![image](https://user-images.githubusercontent.com/38337092/168209986-a6c4e59c-acad-44f7-a77d-4793ac01d2f6.png)

**Comment by rparak** [comment]
You need the correct version of **Unity (2020.1.8f1or later)** and of course you need **Blender + HDRI** package installed on your computer. If Unity and Blender are installed correctly, you can download the project again and/or reinstall Unity. You need to add the **Universal_Robots_Unity_App** folder to Unity.

**Comment by Steedalion** [comment]
Hi Roman, I performed "Reimport All" Assets in unity and it fixed the issue. Thanks.
